import './globals.css'
import { Roboto_Mono } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/footer'

const robotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'GitHub Finder',
  description: 'Generated by Claudio Baeza',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotoMono.className}>
       <div className='min-h-screen grid place-content-center bg-blue-50 dark:bg-blue-950'>
        <div className='sm:w-[500px] md:w-[600px] lg:w-[760px] px-4'>
          <Navbar />
          {children}
          <Footer />
        </div>
       </div>
      </body>
    </html>
  )
}
